begin;

create temporary table imported_flashcard_seed (
  id uuid primary key,
  certification_code text not null,
  lesson_slug text not null,
  front_text text not null,
  back_text text not null,
  hint text,
  is_published boolean not null,
  source_reference text not null,
  source_order integer not null
) on commit drop;

insert into imported_flashcard_seed (
  id,
  certification_code,
  lesson_slug,
  front_text,
  back_text,
  hint,
  is_published,
  source_reference,
  source_order
)
values
  ('71000000-0000-4000-8000-000000000001', 'az-900', 'what-is-cloud-computing', 'Qual é a principal diferença entre cloud computing e um data center on-premises tradicional?', 'Na nuvem, a infraestrutura é fornecida e mantida por um provedor externo, cobrada conforme o uso. No modelo on-premises, a empresa compra, instala e mantém todo o hardware por conta própria.', 'Pense em quem é o dono do hardware.', true, 'Microsoft Learn — Describe cloud concepts', 1),
  ('71000000-0000-4000-8000-000000000002', 'az-900', 'what-is-cloud-computing', 'O que significa "provisionamento sob demanda" na computação em nuvem?', 'É a capacidade de solicitar e obter recursos de TI, como servidores ou armazenamento, de forma imediata e automática, sem precisar aguardar a compra ou instalação de hardware físico.', null, true, 'Microsoft Learn — Describe cloud concepts', 2),
  ('71000000-0000-4000-8000-000000000003', 'az-900', 'what-is-cloud-computing', 'Por que uma startup normalmente prefere usar nuvem em vez de comprar servidores próprios?', 'Porque evita o alto investimento inicial em hardware, permite começar pequeno e escalar conforme o crescimento, além de pagar apenas pelos recursos efetivamente utilizados.', 'Relacione com o modelo financeiro CapEx x OpEx.', true, 'Microsoft Learn — Describe cloud concepts', 3),
  ('71000000-0000-4000-8000-000000000004', 'az-900', 'what-is-cloud-computing', 'O que caracteriza o modelo "pagar conforme o uso" (pay-as-you-go) na nuvem?', 'O cliente paga apenas pelos recursos que efetivamente consome, sem contratos de longo prazo obrigatórios nem necessidade de estimar capacidade futura com antecedência.', null, true, 'Microsoft Learn — Describe cloud concepts', 4),
  ('71000000-0000-4000-8000-000000000005', 'az-900', 'shared-responsibility-model', 'No modelo de responsabilidade compartilhada, quem é sempre responsável pelos dados e pelas identidades, em qualquer tipo de serviço?', 'O cliente. Independentemente de o serviço ser IaaS, PaaS ou SaaS, a proteção dos dados, dos dispositivos e das identidades permanece sempre sob responsabilidade do cliente.', null, true, 'Microsoft Learn — Describe the shared responsibility model', 5),
  ('71000000-0000-4000-8000-000000000006', 'az-900', 'shared-responsibility-model', 'Em um serviço IaaS, quem é responsável por aplicar patches no sistema operacional das máquinas virtuais?', 'O cliente. Em IaaS, o provedor cuida apenas da infraestrutura física, enquanto o cliente gerencia o sistema operacional, incluindo atualizações e patches de segurança.', 'Compare com o nível de controle que o cliente tem em IaaS.', true, 'Microsoft Learn — Describe the shared responsibility model', 6),
  ('71000000-0000-4000-8000-000000000007', 'az-900', 'shared-responsibility-model', 'Como a responsabilidade pelo sistema operacional muda ao migrar de IaaS para PaaS?', 'Em PaaS, o provedor passa a gerenciar o sistema operacional e o runtime da aplicação. O cliente fica responsável apenas pelo código da aplicação e pelos dados.', null, true, 'Microsoft Learn — Describe the shared responsibility model', 7),
  ('71000000-0000-4000-8000-000000000008', 'az-900', 'shared-responsibility-model', 'Em um serviço SaaS, qual responsabilidade de segurança ainda permanece com o cliente?', 'Mesmo em SaaS, o cliente continua responsável por gerenciar seus dados, controlar o acesso de usuários e proteger as credenciais de login usadas no serviço.', null, true, 'Microsoft Learn — Describe the shared responsibility model', 8),
  ('71000000-0000-4000-8000-000000000009', 'az-900', 'public-private-hybrid-cloud', 'Qual é a principal diferença entre nuvem pública e nuvem privada?', 'Na nuvem pública, a infraestrutura é compartilhada entre vários clientes e operada por um provedor terceirizado. Na nuvem privada, a infraestrutura é dedicada a uma única organização.', null, true, 'Microsoft Learn — Describe cloud models', 9),
  ('71000000-0000-4000-8000-000000000010', 'az-900', 'public-private-hybrid-cloud', 'Em qual cenário uma empresa normalmente escolheria um modelo híbrido de nuvem?', 'Quando precisa manter dados sensíveis ou sistemas legados em ambiente privado por questões de conformidade, mas também quer aproveitar a escalabilidade e os serviços da nuvem pública.', 'Pense em uma empresa com requisitos regulatórios rígidos.', true, 'Microsoft Learn — Describe cloud models', 10),
  ('71000000-0000-4000-8000-000000000011', 'az-900', 'public-private-hybrid-cloud', 'Qual é uma desvantagem comum da nuvem privada em comparação com a nuvem pública?', 'Exige investimento inicial maior em hardware e equipe especializada, além de limitar a elasticidade, já que a capacidade disponível é restrita à infraestrutura própria da organização.', null, true, 'Microsoft Learn — Describe cloud models', 11),
  ('71000000-0000-4000-8000-000000000012', 'az-900', 'public-private-hybrid-cloud', 'O que caracteriza o modelo de nuvem híbrida?', 'Combina nuvem pública e nuvem privada, permitindo que dados e aplicações sejam compartilhados entre os dois ambientes conforme a necessidade da organização.', null, true, 'Microsoft Learn — Describe cloud models', 12),
  ('71000000-0000-4000-8000-000000000013', 'az-900', 'choosing-a-cloud-model', 'Quais fatores influenciam a escolha entre nuvem pública, privada ou híbrida para uma organização?', 'Requisitos de conformidade e segurança, custo disponível, necessidade de controle sobre a infraestrutura, presença de sistemas legados e a previsibilidade de demanda por recursos.', null, true, 'Microsoft Learn — Describe cloud models', 13),
  ('71000000-0000-4000-8000-000000000014', 'az-900', 'choosing-a-cloud-model', 'Uma empresa do setor financeiro, com forte exigência regulatória, mas que também quer reduzir custos operacionais. Qual modelo de nuvem tende a ser mais adequado?', 'O modelo híbrido, pois permite manter dados sensíveis sob controle direto em ambiente privado, ao mesmo tempo em que aproveita a nuvem pública para cargas de trabalho menos críticas.', null, true, 'Microsoft Learn — Describe cloud models', 14),
  ('71000000-0000-4000-8000-000000000015', 'az-900', 'choosing-a-cloud-model', 'Por que a nuvem pública costuma ser a escolha mais econômica para cargas de trabalho variáveis?', 'Porque cobra apenas pelo consumo real, eliminando a necessidade de investir em capacidade extra para picos de demanda que nem sempre ocorrem.', null, true, 'Microsoft Learn — Describe cloud models', 15),
  ('71000000-0000-4000-8000-000000000016', 'az-900', 'choosing-a-cloud-model', 'O que significa "residência de dados" ao decidir entre modelos de nuvem?', 'É a exigência de que os dados de uma organização permaneçam armazenados fisicamente dentro de um país ou região específica, o que pode influenciar a escolha do provedor e da localização dos recursos.', null, true, 'Microsoft Learn — Describe cloud models', 16),
  ('71000000-0000-4000-8000-000000000017', 'az-900', 'consumption-based-model', 'O que caracteriza o modelo de consumo (consumption-based model) usado na nuvem?', 'O cliente paga apenas pelos recursos que utiliza, quando os utiliza, sem custos fixos antecipados e sem necessidade de comprar capacidade que talvez nunca seja usada.', null, true, 'Microsoft Learn — Describe cloud concepts', 17),
  ('71000000-0000-4000-8000-000000000018', 'az-900', 'consumption-based-model', 'Como o modelo de consumo reduz o risco financeiro de uma empresa ao adotar a nuvem?', 'Elimina a necessidade de grandes investimentos antecipados em hardware, permitindo ajustar os gastos conforme a demanda real do negócio, com menor exposição a desperdício de capacidade.', null, true, 'Microsoft Learn — Describe cloud concepts', 18),
  ('71000000-0000-4000-8000-000000000019', 'az-900', 'consumption-based-model', 'No modelo de consumo, o que acontece com o custo quando os recursos são desligados ou removidos?', 'O cliente deixa de pagar por eles. A cobrança ocorre apenas enquanto os recursos estão ativos e em uso, refletindo diretamente o consumo real.', null, true, 'Microsoft Learn — Describe cloud concepts', 19),
  ('71000000-0000-4000-8000-000000000020', 'az-900', 'consumption-based-model', 'O modelo de consumo elimina totalmente a necessidade de planejamento de capacidade?', 'Não elimina totalmente, mas reduz bastante o risco, já que os recursos podem ser ajustados rapidamente conforme a demanda real, em vez de depender de estimativas de longo prazo.', null, true, 'Microsoft Learn — Describe cloud concepts', 20),
  ('71000000-0000-4000-8000-000000000021', 'az-900', 'capex-vs-opex', 'Qual é a diferença entre CapEx e OpEx?', 'CapEx (despesa de capital) é o investimento antecipado em ativos físicos, como servidores. OpEx (despesa operacional) é o gasto contínuo conforme o uso, típico do modelo de nuvem.', null, true, 'Microsoft Learn — Describe cloud concepts', 21),
  ('71000000-0000-4000-8000-000000000022', 'az-900', 'capex-vs-opex', 'Por que a adoção da nuvem é geralmente descrita como uma mudança de CapEx para OpEx?', 'Porque a empresa deixa de investir grandes valores antecipados em hardware próprio e passa a pagar despesas recorrentes com base no consumo real dos serviços de nuvem.', null, true, 'Microsoft Learn — Describe cloud concepts', 22),
  ('71000000-0000-4000-8000-000000000023', 'az-900', 'capex-vs-opex', 'Qual vantagem financeira o modelo OpEx oferece em relação ao CapEx?', 'Maior flexibilidade de caixa, já que os gastos são distribuídos ao longo do tempo e podem ser ajustados rapidamente conforme a necessidade, sem imobilizar capital em ativos.', null, true, 'Microsoft Learn — Describe cloud concepts', 23),
  ('71000000-0000-4000-8000-000000000024', 'az-900', 'capex-vs-opex', 'Em qual desses modelos, CapEx ou OpEx, o gasto costuma ser tratado como despesa operacional corrente do mesmo período?', 'No modelo OpEx, os gastos são tratados como despesas operacionais correntes, geralmente reconhecidas no período em que ocorrem, diferente do CapEx, que costuma ser depreciado ao longo do tempo.', null, true, 'Microsoft Learn — Describe cloud concepts', 24),
  ('71000000-0000-4000-8000-000000000025', 'az-900', 'serverless-computing', 'O que é computação serverless?', 'Um modelo em que o provedor de nuvem gerencia toda a infraestrutura de servidores automaticamente, permitindo que o desenvolvedor foque apenas no código da aplicação.', null, true, 'Microsoft Learn — Describe cloud concepts', 25),
  ('71000000-0000-4000-8000-000000000026', 'az-900', 'serverless-computing', 'Apesar do nome, "serverless" significa que não existem servidores envolvidos?', 'Não. Servidores continuam existindo e executando o código, mas sua gestão, provisionamento e escalonamento ficam totalmente a cargo do provedor de nuvem, invisíveis para o desenvolvedor.', null, true, 'Microsoft Learn — Describe cloud concepts', 26),
  ('71000000-0000-4000-8000-000000000027', 'az-900', 'serverless-computing', 'Qual serviço do Azure é o principal exemplo de computação serverless?', 'O Azure Functions, que executa pequenos blocos de código em resposta a eventos, sem que o cliente precise provisionar ou gerenciar servidores.', null, true, 'Microsoft Learn — Describe cloud concepts', 27),
  ('71000000-0000-4000-8000-000000000028', 'az-900', 'serverless-computing', 'Como o modelo de cobrança do serverless normalmente funciona?', 'A cobrança costuma ser baseada no tempo de execução real do código e no número de execuções, em vez de um servidor permanentemente ativo.', null, true, 'Microsoft Learn — Describe cloud concepts', 28),
  ('71000000-0000-4000-8000-000000000029', 'az-900', 'high-availability', 'O que significa alta disponibilidade (high availability) em um sistema na nuvem?', 'É a capacidade de um sistema permanecer operacional e acessível por um período máximo de tempo definido, minimizando interrupções mesmo diante de falhas de componentes.', null, true, 'Microsoft Learn — Describe cloud concepts', 29),
  ('71000000-0000-4000-8000-000000000030', 'az-900', 'high-availability', 'Como o Azure expressa formalmente o nível de alta disponibilidade prometido para um serviço?', 'Por meio de um SLA (Service Level Agreement), que define o percentual de tempo de atividade garantido pelo provedor para aquele serviço específico.', null, true, 'Microsoft Learn — Describe cloud concepts', 30),
  ('71000000-0000-4000-8000-000000000031', 'az-900', 'high-availability', 'Qual recurso de infraestrutura do Azure ajuda a aumentar a alta disponibilidade de uma aplicação?', 'O uso de Availability Zones, que distribuem os recursos entre datacenters fisicamente separados dentro de uma região, reduzindo o impacto de falhas locais.', null, true, 'Microsoft Learn — Describe cloud concepts', 31),
  ('71000000-0000-4000-8000-000000000032', 'az-900', 'high-availability', 'Alta disponibilidade garante que um sistema nunca terá indisponibilidade?', 'Não. Alta disponibilidade busca minimizar o tempo de indisponibilidade dentro de um limite aceitável definido em contrato, mas não elimina completamente a possibilidade de falhas.', null, true, 'Microsoft Learn — Describe cloud concepts', 32),
  ('71000000-0000-4000-8000-000000000033', 'az-900', 'scalability', 'O que diferencia escalabilidade horizontal da vertical?', 'A escala horizontal altera a quantidade de instâncias. A escala vertical aumenta ou reduz a capacidade de uma instância.', null, true, 'Microsoft Learn — Describe cloud concepts', 33),
  ('71000000-0000-4000-8000-000000000034', 'az-900', 'scalability', 'Qual é uma limitação típica da escala vertical em comparação com a escala horizontal?', 'A escala vertical costuma ter um limite máximo de hardware suportado por uma única instância, enquanto a escala horizontal pode, em teoria, adicionar instâncias quase sem limite.', null, true, 'Microsoft Learn — Describe cloud concepts', 34),
  ('71000000-0000-4000-8000-000000000035', 'az-900', 'scalability', 'Em qual cenário a escala horizontal é preferível à escala vertical?', 'Quando a aplicação precisa lidar com grandes picos de tráfego distribuindo a carga entre várias instâncias, mantendo a disponibilidade mesmo se uma instância falhar.', null, true, 'Microsoft Learn — Describe cloud concepts', 35),
  ('71000000-0000-4000-8000-000000000036', 'az-900', 'scalability', 'Escalar verticalmente uma Máquina Virtual do Azure normalmente exige o quê?', 'Costuma exigir a reinicialização da máquina para aplicar o novo tamanho (SKU), já que a capacidade de CPU e memória da instância está sendo alterada diretamente.', null, true, 'Microsoft Learn — Describe cloud concepts', 36),
  ('71000000-0000-4000-8000-000000000037', 'az-900', 'elasticity', 'O que é elasticidade na computação em nuvem?', 'É a capacidade de um sistema aumentar ou reduzir automaticamente os recursos alocados conforme a demanda muda ao longo do tempo, sem intervenção manual constante.', null, true, 'Microsoft Learn — Describe cloud concepts', 37),
  ('71000000-0000-4000-8000-000000000038', 'az-900', 'elasticity', 'Qual é a diferença principal entre escalabilidade e elasticidade?', 'Escalabilidade é a capacidade de o sistema suportar crescimento de carga, enquanto elasticidade é a capacidade de ajustar recursos automaticamente para cima ou para baixo conforme a demanda oscila.', null, true, 'Microsoft Learn — Describe cloud concepts', 38),
  ('71000000-0000-4000-8000-000000000039', 'az-900', 'elasticity', 'Como a elasticidade ajuda a reduzir custos na nuvem?', 'Permite que recursos sejam desligados ou reduzidos automaticamente quando a demanda cai, evitando pagar por capacidade ociosa fora dos horários de pico.', null, true, 'Microsoft Learn — Describe cloud concepts', 39),
  ('71000000-0000-4000-8000-000000000040', 'az-900', 'elasticity', 'Qual serviço do Azure é um exemplo direto de elasticidade automática de recursos?', 'O Azure Autoscale, disponível para Virtual Machine Scale Sets e App Service, que ajusta automaticamente o número de instâncias com base em métricas de uso definidas.', null, true, 'Microsoft Learn — Describe cloud concepts', 40),
  ('71000000-0000-4000-8000-000000000041', 'az-900', 'reliability', 'O que significa confiabilidade (reliability) de um sistema na nuvem?', 'É a capacidade do sistema de se recuperar de falhas e continuar funcionando corretamente, mesmo diante de interrupções, problemas de hardware ou desastres.', null, true, 'Microsoft Learn — Describe cloud concepts', 41),
  ('71000000-0000-4000-8000-000000000042', 'az-900', 'reliability', 'Qual é a diferença entre confiabilidade e alta disponibilidade?', 'Alta disponibilidade foca em manter o sistema no ar pelo maior tempo possível. Confiabilidade foca na capacidade de se recuperar de falhas e continuar entregando o resultado esperado.', null, true, 'Microsoft Learn — Describe cloud concepts', 42),
  ('71000000-0000-4000-8000-000000000043', 'az-900', 'reliability', 'Qual estratégia de infraestrutura no Azure contribui diretamente para aumentar a confiabilidade de uma aplicação?', 'Distribuir os recursos entre múltiplas regiões ou Availability Zones, garantindo que uma falha localizada não interrompa totalmente o funcionamento do sistema.', null, true, 'Microsoft Learn — Describe cloud concepts', 43),
  ('71000000-0000-4000-8000-000000000044', 'az-900', 'reliability', 'Um backup automatizado de dados contribui para qual atributo do sistema: confiabilidade ou elasticidade?', 'Confiabilidade, pois o backup permite que o sistema se recupere de uma falha ou perda de dados e volte a funcionar corretamente.', null, true, 'Microsoft Learn — Describe cloud concepts', 44),
  ('71000000-0000-4000-8000-000000000045', 'az-900', 'predictability', 'O que é previsibilidade de desempenho (performance predictability) na nuvem?', 'É a capacidade de prever como um sistema vai se comportar sob diferentes níveis de carga, garantindo consistência nos tempos de resposta e na experiência do usuário.', null, true, 'Microsoft Learn — Describe cloud concepts', 45),
  ('71000000-0000-4000-8000-000000000046', 'az-900', 'predictability', 'O que é previsibilidade de custo (cost predictability) na nuvem?', 'É a capacidade de estimar com precisão quanto será gasto com os recursos de nuvem, usando ferramentas de orçamento e monitoramento de consumo.', null, true, 'Microsoft Learn — Describe cloud concepts', 46),
  ('71000000-0000-4000-8000-000000000047', 'az-900', 'predictability', 'Qual ferramenta do Azure ajuda diretamente na previsibilidade de custos?', 'A Calculadora de Preços do Azure e o Azure Cost Management, que permitem estimar e acompanhar os gastos antes e durante o uso dos recursos.', null, true, 'Microsoft Learn — Describe cloud concepts', 47),
  ('71000000-0000-4000-8000-000000000048', 'az-900', 'predictability', 'Como o uso de orçamentos (budgets) no Azure Cost Management contribui para a previsibilidade de custos?', 'Permite definir limites de gastos e receber alertas quando o consumo se aproxima do valor definido, ajudando a evitar surpresas na fatura mensal.', null, true, 'Microsoft Learn — Describe cloud concepts', 48),
  ('71000000-0000-4000-8000-000000000049', 'az-900', 'security-and-governance-benefits', 'Quais benefícios de segurança a nuvem oferece que seriam difíceis de replicar internamente?', 'Investimentos massivos em segurança física dos datacenters, monitoramento contínuo de ameaças e certificações de conformidade mantidas por equipes especializadas do provedor.', null, true, 'Microsoft Learn — Describe cloud concepts', 49),
  ('71000000-0000-4000-8000-000000000050', 'az-900', 'security-and-governance-benefits', 'Como a nuvem ajuda organizações a atender requisitos de conformidade regulatória?', 'Os provedores de nuvem mantêm certificações reconhecidas internacionalmente e disponibilizam ferramentas de auditoria, facilitando que os clientes comprovem conformidade com leis e normas do setor.', null, true, 'Microsoft Learn — Describe cloud concepts', 50),
  ('71000000-0000-4000-8000-000000000051', 'az-900', 'security-and-governance-benefits', 'O que se entende por governança na nuvem?', 'É o conjunto de políticas, processos e controles usados para garantir que os recursos de nuvem sejam usados de forma consistente, segura e alinhada às regras da organização.', null, true, 'Microsoft Learn — Describe cloud concepts', 51),
  ('71000000-0000-4000-8000-000000000052', 'az-900', 'security-and-governance-benefits', 'Qual é a diferença entre segurança e governança no contexto de benefícios da nuvem?', 'Segurança trata da proteção dos sistemas e dados contra ameaças. Governança trata das políticas e controles usados para garantir que os recursos sejam usados de forma correta e consistente.', null, true, 'Microsoft Learn — Describe cloud concepts', 52),
  ('71000000-0000-4000-8000-000000000053', 'az-900', 'manageability', 'O que significa "gerenciabilidade da nuvem" (manage in the cloud)?', 'Refere-se a monitorar, configurar e manter a saúde dos recursos hospedados na nuvem, incluindo alertas, métricas de desempenho e ajustes automáticos.', null, true, 'Microsoft Learn — Describe cloud concepts', 53),
  ('71000000-0000-4000-8000-000000000054', 'az-900', 'manageability', 'O que significa "gerenciabilidade sobre a nuvem" (manage from the cloud)?', 'Refere-se à capacidade de administrar remotamente a infraestrutura por meio de interfaces como o portal Azure, CLI ou PowerShell, de qualquer lugar com acesso à internet.', null, true, 'Microsoft Learn — Describe cloud concepts', 54),
  ('71000000-0000-4000-8000-000000000055', 'az-900', 'manageability', 'Dê um exemplo prático de gerenciabilidade "in the cloud" oferecida pelo Azure.', 'O escalonamento automático (autoscale), que ajusta a quantidade de instâncias de um serviço automaticamente com base em métricas como uso de CPU.', null, true, 'Microsoft Learn — Describe cloud concepts', 55),
  ('71000000-0000-4000-8000-000000000056', 'az-900', 'manageability', 'O portal do Azure é um exemplo de gerenciabilidade "in the cloud" ou "from the cloud"?', '"From the cloud", pois é uma ferramenta usada para administrar remotamente os recursos hospedados no Azure, a partir de qualquer lugar com acesso à internet.', null, true, 'Microsoft Learn — Describe cloud concepts', 56),
  ('71000000-0000-4000-8000-000000000057', 'az-900', 'infrastructure-as-a-service', 'O que caracteriza o modelo IaaS?', 'O provedor entrega a infraestrutura básica, como servidores virtuais, rede e armazenamento, enquanto o cliente é responsável por instalar e gerenciar sistemas operacionais e aplicações.', null, true, 'Microsoft Learn — Describe cloud service types', 57),
  ('71000000-0000-4000-8000-000000000058', 'az-900', 'infrastructure-as-a-service', 'Qual é um exemplo de serviço Azure classificado como IaaS?', 'As Máquinas Virtuais do Azure (Azure Virtual Machines), nas quais o cliente controla o sistema operacional e as aplicações instaladas sobre a infraestrutura fornecida.', null, true, 'Microsoft Learn — Describe cloud service types', 58),
  ('71000000-0000-4000-8000-000000000059', 'az-900', 'infrastructure-as-a-service', 'Em qual cenário o IaaS é a escolha mais adequada?', 'Quando a empresa precisa de controle total sobre o sistema operacional e a configuração da infraestrutura, como ao migrar uma aplicação legada sem alterar seu código.', null, true, 'Microsoft Learn — Describe cloud service types', 59),
  ('71000000-0000-4000-8000-000000000060', 'az-900', 'infrastructure-as-a-service', 'No modelo IaaS, o que o provedor de nuvem NÃO gerencia por padrão?', 'O provedor não gerencia o sistema operacional, o runtime, os dados nem as aplicações instaladas dentro das máquinas virtuais; essas responsabilidades permanecem com o cliente.', null, true, 'Microsoft Learn — Describe cloud service types', 60),
  ('71000000-0000-4000-8000-000000000061', 'az-900', 'platform-as-a-service', 'O que caracteriza o modelo PaaS?', 'O provedor gerencia a infraestrutura e o sistema operacional, entregando um ambiente pronto para que o cliente desenvolva, teste e implante aplicações sem se preocupar com a base.', null, true, 'Microsoft Learn — Describe cloud service types', 61),
  ('71000000-0000-4000-8000-000000000062', 'az-900', 'platform-as-a-service', 'Qual é um exemplo de serviço Azure classificado como PaaS?', 'O Azure App Service, que permite hospedar aplicações web sem que o cliente precise gerenciar servidores ou sistemas operacionais.', null, true, 'Microsoft Learn — Describe cloud service types', 62),
  ('71000000-0000-4000-8000-000000000063', 'az-900', 'platform-as-a-service', 'Qual é a principal vantagem do PaaS para equipes de desenvolvimento?', 'Permite que os desenvolvedores foquem no código da aplicação, reduzindo o tempo gasto com configuração e manutenção de infraestrutura e sistema operacional.', null, true, 'Microsoft Learn — Describe cloud service types', 63),
  ('71000000-0000-4000-8000-000000000064', 'az-900', 'platform-as-a-service', 'Em PaaS, o que o cliente ainda precisa gerenciar, mesmo com a infraestrutura sendo cuidada pelo provedor?', 'O cliente continua responsável pelo código da aplicação, pelos dados e pelas configurações específicas da aplicação implantada na plataforma.', null, true, 'Microsoft Learn — Describe cloud service types', 64),
  ('71000000-0000-4000-8000-000000000065', 'az-900', 'software-as-a-service', 'O que caracteriza o modelo SaaS?', 'O provedor entrega uma aplicação completa e pronta para uso pela internet, cuidando de toda a infraestrutura, plataforma e manutenção do software.', null, true, 'Microsoft Learn — Describe cloud service types', 65),
  ('71000000-0000-4000-8000-000000000066', 'az-900', 'software-as-a-service', 'Qual é um exemplo comum de aplicação SaaS?', 'O Microsoft 365, que fornece aplicativos como e-mail e ferramentas de produtividade prontos para uso, sem necessidade de instalação ou manutenção de infraestrutura pelo cliente.', null, true, 'Microsoft Learn — Describe cloud service types', 66),
  ('71000000-0000-4000-8000-000000000067', 'az-900', 'software-as-a-service', 'Qual é a principal responsabilidade do cliente ao usar um serviço SaaS?', 'Gerenciar os dados inseridos na aplicação e controlar quais usuários têm acesso a ela, já que toda a infraestrutura e o software são geridos pelo provedor.', null, true, 'Microsoft Learn — Describe cloud service types', 67),
  ('71000000-0000-4000-8000-000000000068', 'az-900', 'software-as-a-service', 'Por que o SaaS costuma ser o modelo com menor esforço técnico exigido do cliente?', 'Porque o provedor gerencia toda a pilha, desde a infraestrutura até a própria aplicação, deixando ao cliente apenas a configuração de uso e a gestão de usuários e dados.', null, true, 'Microsoft Learn — Describe cloud service types', 68),
  ('71000000-0000-4000-8000-000000000069', 'az-900', 'choosing-iaas-paas-saas', 'Uma empresa quer migrar um sistema legado sem reescrever o código. Qual modelo de serviço é mais indicado?', 'IaaS, pois oferece controle total sobre o sistema operacional e a infraestrutura, permitindo hospedar aplicações existentes sem a necessidade de adaptá-las a uma plataforma gerenciada.', null, true, 'Microsoft Learn — Describe cloud service types', 69),
  ('71000000-0000-4000-8000-000000000070', 'az-900', 'choosing-iaas-paas-saas', 'Uma equipe de desenvolvimento quer publicar rapidamente uma aplicação web sem gerenciar servidores. Qual modelo é mais indicado?', 'PaaS, pois fornece um ambiente pronto para implantação de aplicações, eliminando a necessidade de configurar e manter servidores e sistemas operacionais.', null, true, 'Microsoft Learn — Describe cloud service types', 70),
  ('71000000-0000-4000-8000-000000000071', 'az-900', 'choosing-iaas-paas-saas', 'Uma empresa quer usar um sistema de e-mail corporativo sem instalar nada localmente. Qual modelo é mais indicado?', 'SaaS, pois entrega a aplicação completa e pronta para uso, sem exigir que a empresa gerencie infraestrutura, plataforma ou o próprio software.', null, true, 'Microsoft Learn — Describe cloud service types', 71),
  ('71000000-0000-4000-8000-000000000072', 'az-900', 'choosing-iaas-paas-saas', 'De forma geral, à medida que se avança de IaaS para PaaS e depois para SaaS, o que acontece com o controle e a responsabilidade técnica do cliente?', 'O controle e a responsabilidade técnica do cliente diminuem progressivamente, enquanto a responsabilidade do provedor de nuvem aumenta a cada modelo.', null, true, 'Microsoft Learn — Describe cloud service types', 72),
  ('71000000-0000-4000-8000-000000000073', 'az-900', 'azure-datacenters', 'O que é um datacenter no contexto do Azure?', 'Uma instalação física que abriga servidores, armazenamento e equipamentos de rede usados para hospedar os serviços de nuvem do Azure.', null, true, 'Microsoft Learn — Describe Azure architecture components', 73),
  ('71000000-0000-4000-8000-000000000074', 'az-900', 'azure-datacenters', 'Como os datacenters do Azure se relacionam com as regiões?', 'Uma região do Azure é composta por um ou mais datacenters conectados por uma rede de baixa latência, funcionando de forma integrada para oferecer os serviços da nuvem.', null, true, 'Microsoft Learn — Describe Azure architecture components', 74),
  ('71000000-0000-4000-8000-000000000075', 'az-900', 'azure-datacenters', 'Os clientes do Azure têm acesso direto para visitar ou gerenciar fisicamente os datacenters?', 'Não. Os datacenters são geridos exclusivamente pela Microsoft, seguindo rígidos controles de segurança física, e não são acessíveis diretamente pelos clientes.', null, true, 'Microsoft Learn — Describe Azure architecture components', 75),
  ('71000000-0000-4000-8000-000000000076', 'az-900', 'azure-datacenters', 'Qual é a relação entre "datacenter" e "região" nos termos usados pelo Azure?', 'Um datacenter é uma instalação física individual, enquanto uma região é um agrupamento geográfico de um ou mais datacenters, conectados por rede de baixa latência.', null, true, 'Microsoft Learn — Describe Azure architecture components', 76),
  ('71000000-0000-4000-8000-000000000077', 'az-900', 'azure-regions', 'Por que uma empresa pode preferir implantar seus recursos na região do Azure mais próxima de seus usuários?', 'Para reduzir a latência de rede, melhorando o tempo de resposta das aplicações e a experiência do usuário final.', null, true, 'Microsoft Learn — Describe Azure architecture components', 77),
  ('71000000-0000-4000-8000-000000000078', 'az-900', 'azure-regions', 'Por que a escolha da região do Azure pode impactar a conformidade regulatória de uma empresa?', 'Porque algumas leis exigem que dados de determinados países ou setores permaneçam armazenados dentro de fronteiras geográficas específicas, o que é chamado de residência de dados.', null, true, 'Microsoft Learn — Describe Azure architecture components', 78),
  ('71000000-0000-4000-8000-000000000079', 'az-900', 'azure-regions', 'Todos os serviços do Azure estão disponíveis em todas as regiões?', 'Não. A disponibilidade de determinados serviços pode variar entre regiões, sendo necessário verificar quais recursos estão habilitados na região escolhida antes de planejar uma implantação.', null, true, 'Microsoft Learn — Describe Azure architecture components', 79),
  ('71000000-0000-4000-8000-000000000080', 'az-900', 'azure-regions', 'Uma empresa precisa hospedar um serviço específico que não está disponível na região mais próxima de seus clientes. O que ela deve considerar?', 'Avaliar regiões alternativas que ofereçam o serviço necessário, ponderando o possível aumento de latência contra a necessidade de usar aquele recurso específico.', null, true, 'Microsoft Learn — Describe Azure architecture components', 80),
  ('71000000-0000-4000-8000-000000000081', 'az-900', 'availability-zones', 'Qual é a característica física das Availability Zones dentro de uma mesma região do Azure?', 'São datacenters fisicamente separados, cada um com fornecimento de energia, refrigeração e rede independentes, reduzindo o risco de uma falha afetar mais de uma zona.', null, true, 'Microsoft Learn — Describe Azure architecture components', 81),
  ('71000000-0000-4000-8000-000000000082', 'az-900', 'availability-zones', 'Quantas Availability Zones, no mínimo, uma região do Azure habilitada para zonas costuma oferecer?', 'No mínimo três zonas de disponibilidade separadas fisicamente, permitindo distribuir recursos de forma redundante dentro da mesma região.', null, true, 'Microsoft Learn — Describe Azure architecture components', 82),
  ('71000000-0000-4000-8000-000000000083', 'az-900', 'availability-zones', 'Qual é a diferença entre usar Availability Zones e usar um Availability Set para alta disponibilidade?', 'Availability Zones distribuem recursos entre datacenters fisicamente separados dentro da região. Availability Sets distribuem recursos dentro de um único datacenter, entre diferentes racks de hardware.', null, true, 'Microsoft Learn — Describe Azure architecture components', 83),
  ('71000000-0000-4000-8000-000000000084', 'az-900', 'availability-zones', 'Availability Zones estão disponíveis em todas as regiões do Azure?', 'Não. Apenas regiões habilitadas para zonas de disponibilidade oferecem esse recurso; nem todas as regiões do Azure suportam Availability Zones.', null, true, 'Microsoft Learn — Describe Azure architecture components', 84),
  ('71000000-0000-4000-8000-000000000085', 'az-900', 'region-pairs-and-sovereign-regions', 'O que é um par de regiões (region pair) no Azure?', 'São duas regiões do Azure associadas dentro da mesma geografia, usadas para replicação de dados e recuperação de desastres, garantindo que uma falha em uma região não afete a outra.', null, true, 'Microsoft Learn — Describe Azure architecture components', 85),
  ('71000000-0000-4000-8000-000000000086', 'az-900', 'region-pairs-and-sovereign-regions', 'Qual é uma vantagem de usar pares de regiões para recuperação de desastres?', 'Se uma região sofrer uma interrupção grave, os serviços e dados podem ser recuperados na região pareada, mantendo a continuidade do negócio.', null, true, 'Microsoft Learn — Describe Azure architecture components', 86),
  ('71000000-0000-4000-8000-000000000087', 'az-900', 'region-pairs-and-sovereign-regions', 'O que são regiões soberanas (sovereign regions) no Azure?', 'São instâncias isoladas do Azure operadas separadamente da nuvem pública global, geralmente para atender requisitos legais específicos de governos ou setores altamente regulados, como o Azure Government.', null, true, 'Microsoft Learn — Describe Azure architecture components', 87),
  ('71000000-0000-4000-8000-000000000088', 'az-900', 'region-pairs-and-sovereign-regions', 'Durante uma atualização planejada da plataforma Azure, como os pares de regiões ajudam a reduzir riscos?', 'A Microsoft normalmente atualiza apenas uma região do par por vez, garantindo que a outra região continue operacional caso ocorra algum problema durante a atualização.', null, true, 'Microsoft Learn — Describe Azure architecture components', 88),
  ('71000000-0000-4000-8000-000000000089', 'az-900', 'resources-and-resource-groups', 'O que acontece com todos os recursos contidos em um grupo de recursos (resource group) quando ele é excluído?', 'Todos os recursos dentro do grupo de recursos são excluídos junto com ele, o que exige atenção antes de remover um grupo de recursos em produção.', null, true, 'Microsoft Learn — Describe Azure architecture components', 89),
  ('71000000-0000-4000-8000-000000000090', 'az-900', 'resources-and-resource-groups', 'Um grupo de recursos pode conter recursos hospedados em regiões diferentes?', 'Sim. Um grupo de recursos pode agrupar recursos de várias regiões, embora o próprio grupo de recursos armazene metadados em uma região específica.', null, true, 'Microsoft Learn — Describe Azure architecture components', 90),
  ('71000000-0000-4000-8000-000000000091', 'az-900', 'resources-and-resource-groups', 'A quantas assinaturas (subscriptions) um grupo de recursos pode pertencer simultaneamente?', 'Apenas uma. Cada grupo de recursos está sempre associado a uma única assinatura do Azure, não podendo ser compartilhado entre assinaturas diferentes.', null, true, 'Microsoft Learn — Describe Azure architecture components', 91),
  ('71000000-0000-4000-8000-000000000092', 'az-900', 'resources-and-resource-groups', 'É possível aplicar tags e políticas diretamente em um grupo de recursos, afetando todos os recursos dentro dele?', 'Sim. Aplicar tags ou políticas em um grupo de recursos permite gerenciar, organizar e controlar de forma centralizada todos os recursos contidos nele.', null, true, 'Microsoft Learn — Describe Azure architecture components', 92),
  ('71000000-0000-4000-8000-000000000093', 'az-900', 'subscriptions-and-management-groups', 'Qual é a principal função de uma assinatura (subscription) do Azure?', 'Definir um limite lógico de faturamento e acesso, agrupando recursos e permitindo controlar custos e permissões de forma isolada de outras assinaturas.', null, true, 'Microsoft Learn — Describe Azure architecture components', 93),
  ('71000000-0000-4000-8000-000000000094', 'az-900', 'subscriptions-and-management-groups', 'Para que servem os grupos de gerenciamento (management groups) no Azure?', 'Para organizar múltiplas assinaturas em uma estrutura hierárquica, permitindo aplicar políticas e controles de acesso de forma consistente a todas as assinaturas de uma vez.', null, true, 'Microsoft Learn — Describe Azure architecture components', 94),
  ('71000000-0000-4000-8000-000000000095', 'az-900', 'subscriptions-and-management-groups', 'Uma organização com várias unidades de negócio quer aplicar a mesma política de segurança a todas as assinaturas de uma vez. Qual recurso do Azure permite isso?', 'Os grupos de gerenciamento, que permitem aplicar políticas e permissões de forma centralizada a um conjunto de assinaturas relacionadas.', null, true, 'Microsoft Learn — Describe Azure architecture components', 95),
  ('71000000-0000-4000-8000-000000000096', 'az-900', 'subscriptions-and-management-groups', 'Uma mesma organização pode ter múltiplas assinaturas do Azure?', 'Sim. É comum que organizações usem múltiplas assinaturas para separar ambientes, departamentos ou projetos, cada uma com seu próprio faturamento e limites de recursos.', null, true, 'Microsoft Learn — Describe Azure architecture components', 96),
  ('71000000-0000-4000-8000-000000000097', 'az-900', 'azure-resource-hierarchy', 'Qual é a ordem correta da hierarquia de recursos do Azure, do nível mais alto ao mais baixo?', 'Grupos de gerenciamento, assinaturas, grupos de recursos e, por fim, os recursos individuais, como máquinas virtuais ou bancos de dados.', null, true, 'Microsoft Learn — Describe Azure architecture components', 97),
  ('71000000-0000-4000-8000-000000000098', 'az-900', 'azure-resource-hierarchy', 'Como as políticas e permissões aplicadas em um nível superior da hierarquia do Azure afetam os níveis inferiores?', 'Elas são herdadas automaticamente pelos níveis inferiores, a menos que sejam explicitamente sobrescritas em um nível mais específico da hierarquia.', null, true, 'Microsoft Learn — Describe Azure architecture components', 98),
  ('71000000-0000-4000-8000-000000000099', 'az-900', 'azure-resource-hierarchy', 'Por que organizar recursos em uma hierarquia clara facilita a governança no Azure?', 'Porque permite aplicar políticas, orçamentos e controles de acesso de forma centralizada, reduzindo o esforço de configurar cada recurso individualmente.', null, true, 'Microsoft Learn — Describe Azure architecture components', 99),
  ('71000000-0000-4000-8000-000000000100', 'az-900', 'azure-resource-hierarchy', 'O que costuma prevalecer quando uma política é aplicada diretamente em um grupo de recursos específico, diferente da política herdada da assinatura?', 'A política mais específica, aplicada no nível do grupo de recursos, normalmente prevalece sobre a política herdada de níveis superiores, salvo restrição explícita em contrário.', null, true, 'Microsoft Learn — Describe Azure architecture components', 100),
  ('71000000-0000-4000-8000-000000000101', 'az-900', 'comparing-compute-options', 'Quando uma carga de trabalho é melhor atendida por uma Máquina Virtual em vez de um contêiner?', 'Quando a aplicação exige controle total sobre o sistema operacional, configurações específicas de baixo nível ou compatibilidade com softwares legados que não foram projetados para contêineres.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 101),
  ('71000000-0000-4000-8000-000000000102', 'az-900', 'comparing-compute-options', 'Em qual cenário uma solução serverless, como o Azure Functions, é mais vantajosa do que uma Máquina Virtual?', 'Quando a carga de trabalho é orientada a eventos, de curta duração e com demanda variável, permitindo pagar apenas pelo tempo de execução, sem manter um servidor sempre ativo.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 102),
  ('71000000-0000-4000-8000-000000000103', 'az-900', 'comparing-compute-options', 'Por que contêineres costumam iniciar mais rapidamente do que Máquinas Virtuais?', 'Porque compartilham o kernel do sistema operacional do host e não precisam inicializar um sistema operacional completo, tornando sua inicialização muito mais leve e rápida.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 103),
  ('71000000-0000-4000-8000-000000000104', 'az-900', 'comparing-compute-options', 'Qual opção de computação do Azure é mais indicada para empacotar uma aplicação com todas as suas dependências, garantindo comportamento consistente em qualquer ambiente?', 'Contêineres, pois empacotam a aplicação junto com suas bibliotecas e dependências, garantindo consistência entre os ambientes de desenvolvimento, teste e produção.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 104),
  ('71000000-0000-4000-8000-000000000105', 'az-900', 'azure-virtual-machines', 'O que é uma Máquina Virtual (VM) do Azure?', 'É um recurso de computação IaaS que emula um computador físico completo, permitindo ao cliente instalar sistema operacional, softwares e configurar a máquina conforme sua necessidade.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 105),
  ('71000000-0000-4000-8000-000000000106', 'az-900', 'azure-virtual-machines', 'Em uma Máquina Virtual do Azure, quem é responsável por instalar atualizações de segurança do sistema operacional?', 'O cliente. O Azure fornece a infraestrutura subjacente, mas a manutenção do sistema operacional dentro da VM é responsabilidade do usuário.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 106),
  ('71000000-0000-4000-8000-000000000107', 'az-900', 'azure-virtual-machines', 'Qual é uma vantagem de usar Máquinas Virtuais do Azure em vez de servidores físicos próprios?', 'Permite provisionar e redimensionar servidores rapidamente, sem investimento em hardware físico, além de pagar apenas pelo tempo em que a VM estiver em execução.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 107),
  ('71000000-0000-4000-8000-000000000108', 'az-900', 'azure-virtual-machines', 'Qual é uma desvantagem de usar Máquinas Virtuais em comparação com serviços PaaS ou serverless?', 'Exige mais esforço de gerenciamento, já que o cliente precisa cuidar do sistema operacional, patches de segurança e configuração da máquina, em vez de focar apenas na aplicação.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 108),
  ('71000000-0000-4000-8000-000000000109', 'az-900', 'vm-scale-sets-and-availability-sets', 'Qual é a principal finalidade dos Virtual Machine Scale Sets no Azure?', 'Permitir a criação e o gerenciamento de um grupo de Máquinas Virtuais idênticas que podem aumentar ou reduzir automaticamente em quantidade, conforme a demanda de carga.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 109),
  ('71000000-0000-4000-8000-000000000110', 'az-900', 'vm-scale-sets-and-availability-sets', 'Qual é a diferença entre um Availability Set e um Virtual Machine Scale Set?', 'O Availability Set distribui VMs existentes entre domínios de falha e atualização para alta disponibilidade. O Scale Set, além disso, escala automaticamente o número de VMs conforme a demanda.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 110),
  ('71000000-0000-4000-8000-000000000111', 'az-900', 'vm-scale-sets-and-availability-sets', 'O que são domínios de falha (fault domains) em um Availability Set?', 'São agrupamentos lógicos de hardware, como racks com fonte de energia e rede próprias, usados para distribuir VMs e reduzir o impacto de uma falha física simultânea.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 111),
  ('71000000-0000-4000-8000-000000000112', 'az-900', 'vm-scale-sets-and-availability-sets', 'O que são domínios de atualização (update domains) em um Availability Set?', 'São grupos lógicos de VMs que permitem que o Azure realize manutenções e reinicializações planejadas de forma escalonada, evitando que todas as VMs fiquem indisponíveis ao mesmo tempo.', null, true, 'Microsoft Learn — Describe Azure compute and networking services', 112);

do $$
declare
  missing_slugs text;
begin
  select string_agg(invalid.lesson_slug, ', ' order by invalid.lesson_slug)
  into missing_slugs
  from (
    select seed.lesson_slug
    from imported_flashcard_seed seed
    left join public.lessons lesson
      on lesson.slug = seed.lesson_slug
    group by seed.lesson_slug
    having count(distinct lesson.id) <> 1
  ) invalid;

  if missing_slugs is not null then
    raise exception 'A importação contém lesson_slug ausente ou ambíguo: %', missing_slugs;
  end if;
end
$$;

with resolved_seed as (
  select
    seed.*,
    lesson.id as lesson_id
  from imported_flashcard_seed seed
  join public.lessons lesson
    on lesson.slug = seed.lesson_slug
),
new_seed as (
  select resolved.*
  from resolved_seed resolved
  where not exists (
    select 1
    from public.flashcards existing
    where existing.id = resolved.id
       or (
         existing.lesson_id = resolved.lesson_id
         and lower(trim(existing.front_text)) = lower(trim(resolved.front_text))
       )
  )
),
ordered_seed as (
  select
    new_seed.*,
    row_number() over (
      partition by new_seed.lesson_id
      order by new_seed.source_order
    )::integer as lesson_offset
  from new_seed
),
existing_order as (
  select
    lesson.id as lesson_id,
    coalesce(max(flashcard.display_order), 0) as max_display_order
  from (select distinct lesson_id as id from ordered_seed) lesson
  left join public.flashcards flashcard
    on flashcard.lesson_id = lesson.id
  group by lesson.id
)
insert into public.flashcards (
  id,
  lesson_id,
  front_text,
  back_text,
  hint,
  display_order,
  is_published
)
select
  ordered.id,
  ordered.lesson_id,
  ordered.front_text,
  ordered.back_text,
  ordered.hint,
  existing.max_display_order + ordered.lesson_offset,
  ordered.is_published
from ordered_seed ordered
join existing_order existing
  on existing.lesson_id = ordered.lesson_id
order by ordered.source_order
on conflict (id) do nothing;

commit;
